name: flutter_learn_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.6
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/gradient.png
    - assets/logo.png
    - assets/logo1.png
    - assets/logo_with_text.png
    - assets/splash.png
    - assets/splash_branding.png
    - assets/splash_background.png
    - assets/thumb.jpg
    - assets/user_image.jpg
  uses-material-design: true
